// <auto-generated />
using System;
using GuiaPlus.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuiaPlus.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GuiaPlus.API.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tbClientes_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPFCNPJ")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)")
                        .HasColumnName("tbClientes_CPFCNPJ");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tbClientes_Email");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tbClientes_NomeCompleto");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tbClientes_Senha");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("tbClientes_Status");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tbClientes_Telefone");

                    b.HasKey("Id");

                    b.HasIndex("CPFCNPJ")
                        .IsUnique();

                    b.ToTable("tbClientes", (string)null);
                });

            modelBuilder.Entity("GuiaPlus.API.Models.ClienteEndereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tbEnderecosClientes_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("tbEnderecosClientes_Bairro");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("tbEnderecosClientes_CEP");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("tbEnderecosClientes_Cidade");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("tbClientes_Id");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tbEnderecosClientes_Complemento");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tbEnderecosClientes_Logradouro");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tbEnderecosClientes_Numero");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("tbEnderecosClientes", (string)null);
                });

            modelBuilder.Entity("GuiaPlus.API.Models.Guia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tbGuias_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteEnderecoId")
                        .HasColumnType("int")
                        .HasColumnName("tbEnderecosClientes_Id");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("tbClientes_Id");

                    b.Property<DateTime?>("DataHoraConfirmouRetirada")
                        .HasColumnType("datetime2")
                        .HasColumnName("tbGuias_DataHoraConfirmouRetirada");

                    b.Property<DateTime?>("DataHoraIniciouColeta")
                        .HasColumnType("datetime2")
                        .HasColumnName("tbGuias_DataHoraIniciouColeta");

                    b.Property<DateTime>("DataHoraRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("tbGuias_DataHoraRegistro");

                    b.Property<string>("NumeroGuia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tbGuias_NumeroGuia");

                    b.Property<int>("ServicoId")
                        .HasColumnType("int")
                        .HasColumnName("tbServicos_Id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("tbGuias_Status");

                    b.HasKey("Id");

                    b.HasIndex("ClienteEnderecoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ServicoId");

                    b.ToTable("tbGuias", (string)null);
                });

            modelBuilder.Entity("GuiaPlus.API.Models.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tbServicos_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tbServicos_Nome");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("tbServicos_Status");

                    b.HasKey("Id");

                    b.ToTable("tbServicos", (string)null);
                });

            modelBuilder.Entity("GuiaPlus.API.Models.ClienteEndereco", b =>
                {
                    b.HasOne("GuiaPlus.API.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GuiaPlus.API.Models.Guia", b =>
                {
                    b.HasOne("GuiaPlus.API.Models.ClienteEndereco", "ClienteEndereco")
                        .WithMany()
                        .HasForeignKey("ClienteEnderecoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GuiaPlus.API.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GuiaPlus.API.Models.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ClienteEndereco");

                    b.Navigation("Servico");
                });
#pragma warning restore 612, 618
        }
    }
}
